name: Build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Use python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.8"

      - name: Deploy project
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: rsoi-lab1-2022-kazakov
          heroku_email: ze17@yandex.ru
          usedocker: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 50
          reporters: cli
